"""M2 happy path: fetch issue → worktree → agent → push → PR open.

This module is the single async entrypoint for ``symphony run-once <n>``.
External effects (gh, git, claude) are factored into module-level helpers so
tests can monkeypatch them without spinning up real subprocesses.

Auto-merge is intentionally not armed at PR-open time. Per SYMPHONY.md (M0
spike findings), Codex's review never satisfies required-reviewer branch
protection — `gh pr merge --auto` would either bypass review entirely (in
repos with no required reviewers) or sit waiting forever. M3's review loop
fires `gh pr merge --squash --delete-branch` directly once the verdict
resolves to Approved and CI is green.
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .agent import run_agent
from .config import Config, load_config
from .github import (
    Issue,
    PR,
    comment_pr,
    name_with_owner,
    open_pr,
    tracked_issues,
    view_issue,
)
from .prompts import make_env, render
from .workspace import ensure_worktree

log = logging.getLogger(__name__)

PR_FOOTER = "---\nAuto-generated by Symphony."


@dataclass(frozen=True)
class RunOnceResult:
    issue_number: int
    pr: PR | None
    skipped: bool
    skip_reason: str | None
    worktree: Path | None


def _head_sha(worktree: Path) -> str:
    """Resolve ``HEAD`` to a full SHA inside the worktree."""
    res = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=worktree,
        check=True,
        capture_output=True,
        text=True,
    )
    return res.stdout.strip()


def _git_push(worktree: Path, branch: str) -> None:
    subprocess.run(
        ["git", "push", "-u", "origin", branch],
        cwd=worktree,
        check=True,
        capture_output=True,
        text=True,
    )


def _build_pr_body(issue: Issue) -> str:
    return f"Closes #{issue.number}\n\n{issue.title}\n\n{PR_FOOTER}\n"


def _satisfied_deps(tracked: list[Any]) -> list[Any]:
    """Filter trackedIssues output to ones closed-as-completed.

    Open issues — and issues closed as `NOT_PLANNED` / `DUPLICATE` — are not
    satisfied dependencies and must not appear in the prompt.
    """
    return [
        t
        for t in tracked
        if t.state == "CLOSED" and (t.state_reason in (None, "COMPLETED"))
    ]


async def run_once(*, issue_number: int, config_path: Path) -> RunOnceResult:
    cfg: Config = load_config(config_path)
    repo_path = cfg.repo.path

    issue = view_issue(issue_number, repo_path=repo_path)
    tracked = tracked_issues(issue_number, repo_path=repo_path)
    deps = _satisfied_deps(tracked)
    owner, name = name_with_owner(repo_path)

    worktree = ensure_worktree(
        repo_path=repo_path,
        worktree_root=cfg.paths.worktree_root,
        repo_name=name,
        issue_number=issue_number,
        base_branch=cfg.repo.default_branch,
        author_name=cfg.git.author_name,
        author_email=cfg.git.author_email,
    )

    env = make_env(cfg.paths.prompts_dir)
    prompt = render(
        env,
        "round1.md.j2",
        {
            "issue": issue,
            "repo": type(
                "RepoCtx",
                (),
                {"owner": owner, "name": name, "default_branch": cfg.repo.default_branch},
            ),
            "worktree_path": str(worktree),
            "satisfied_deps": deps,
        },
    )

    # Snapshot HEAD before the agent runs so we can detect a true no-op even
    # on re-dispatch into a worktree that already has prior commits ahead of
    # origin/<base>. (`git rev-list --count origin/<base>..HEAD` is cumulative
    # and would mistake an already-ahead branch for a successful new run.)
    head_before = _head_sha(worktree)

    result = await run_agent(
        prompt,
        worktree,
        model=cfg.agent.model,
        max_turns=cfg.agent.max_turns,
    )

    if not result.success:
        log.error(
            "agent run failed for issue #%d (exit=%d, is_error=%s); skipping push",
            issue_number,
            result.exit_code,
            result.is_error,
        )
        return RunOnceResult(
            issue_number=issue_number,
            pr=None,
            skipped=True,
            skip_reason="agent-failed",
            worktree=worktree,
        )

    head_after = _head_sha(worktree)
    if head_after == head_before:
        log.error(
            "agent exited cleanly but HEAD did not advance in worktree %s; skipping push",
            worktree,
        )
        return RunOnceResult(
            issue_number=issue_number,
            pr=None,
            skipped=True,
            skip_reason="empty-diff",
            worktree=worktree,
        )

    branch = f"auto/{issue_number}"
    _git_push(worktree, branch)
    pr = open_pr(
        repo_path=repo_path,
        head=branch,
        base=cfg.repo.default_branch,
        title=issue.title,
        body=_build_pr_body(issue),
    )
    comment_pr(repo_path=repo_path, pr_number=pr.number, body="@codex review")
    return RunOnceResult(
        issue_number=issue_number,
        pr=pr,
        skipped=False,
        skip_reason=None,
        worktree=worktree,
    )
